#!/usr/bin/env bash
# Build the books.  Usage:
#   ./build.sh            # run all code, then build both PDFs
#   ./build.sh ml         # Classical Machine Learning only
#   ./build.sh dl         # Deep Learning only
#   SKIP_CODE=1 ./build.sh ml   # reuse gen/ outputs, only run LaTeX
#   ./build.sh test       # the template test book
set -euo pipefail
cd "$(dirname "$0")"
export PYTHONPATH="$PWD/code"
export PYTHONHASHSEED=0
export CUDA_VISIBLE_DEVICES=""
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1

declare -A PDFNAME=( [ml]="Classical Machine Learning.pdf" [dl]="Deep Learning.pdf" [test]="test-book.pdf" )

run_code () {
  local book=$1
  mkdir -p "gen/$book/logs"
  rm -f "gen/$book/checks.log"
  echo ">> running code/$book/*.py"
  local fail=0
  # scripts are independent; run 4 at a time
  ls code/$book/*.py 2>/dev/null | sort | xargs -r -P 4 -I{} bash -c '
    f="{}"; n=$(basename "$f" .py)
    if ! python3 "$f" > "gen/'"$book"'/logs/$n.log" 2>&1; then
      echo "!! $f FAILED"; tail -20 "gen/'"$book"'/logs/$n.log"; exit 255
    fi' || fail=1
  if [ $fail -ne 0 ]; then echo "code failed"; exit 1; fi
  python3 code/extract_snippets.py "$book"
  if [ -f "gen/$book/checks.log" ]; then
    echo ">> library cross-checks passed: $(grep -c -- '-> OK' "gen/$book/checks.log")"
    if grep -q MISMATCH "gen/$book/checks.log"; then echo "MISMATCH found"; exit 1; fi
  fi
}

collect () {
  local book=$1
  mkdir -p "gen/$book"
  { echo "% generated by build.sh"; for f in gen/$book/*.tex; do
      [ "$(basename "$f")" = all.tex ] && continue
      echo "\\input{${f%.tex}}"; done; } > "gen/$book/all.tex"
}

build_pdf () {
  local book=$1
  mkdir -p "chapters/$book"
  latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error "$book.tex" > "build-$book.log" 2>&1 || {
    grep -n -A5 "^!\|:[0-9]*: " "$book.log" | head -40; echo "LaTeX failed (see $book.log)"; exit 1; }
  cp "$book.pdf" "${PDFNAME[$book]}"
  echo ">> built ${PDFNAME[$book]} ($(pdfinfo "$book.pdf" | awk '/^Pages/{print $2}') pages)"
  grep -c "Overfull" "$book.log" | xargs echo ">> overfull boxes:"
  grep -q "undefined" "$book.log" && grep "undefined" "$book.log" | sort -u | head || true
}

books=${1:-all}
[ "$books" = all ] && books="ml dl"
for b in $books; do
  [ -f "$b.tex" ] || { echo "no $b.tex, skipping"; continue; }
  if [ -z "${SKIP_CODE:-}" ] && [ -d "code/$b" ]; then run_code "$b"; fi
  collect "$b"
  build_pdf "$b"
done
