#!/usr/bin/env bash
# Quick draft build of one chapter:  ./draft.sh ml 03-linreg   -> draft-ml.pdf
set -euo pipefail
cd "$(dirname "$0")"
book=$1; ch=$2
export PYTHONPATH="$PWD/code"
python3 code/extract_snippets.py "$book"
{ echo "% generated by draft.sh"; for f in gen/$book/*.tex; do
    [ "$(basename "$f")" = all.tex ] && continue; echo "\\input{${f%.tex}}"; done; } > "gen/$book/all.tex"
for i in 1 2; do
  pdflatex -interaction=nonstopmode -halt-on-error -file-line-error -jobname="draft-$book" \
    "\\includeonly{chapters/$book/$ch}\\input{$book}" > /dev/null 2>&1 || {
    grep -n -A6 "^!\|\.tex:[0-9]*: " "draft-$book.log" | head -40; echo "LaTeX failed"; exit 1; }
done
echo "pages: $(pdfinfo draft-$book.pdf | awk '/^Pages/{print $2}')"
grep -n "Overfull\|gv Warning\|Reference.*undefined" "draft-$book.log" | awk '!/Overfull/ || ($0 ~ /[0-9.]+pt/ && substr($0, match($0,/\(([0-9.]+)pt/)+1, RLENGTH-4)+0 > 2)' | head -20 || true
